image : mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - dotnet restore ./WinArch.csproj
    - dotnet build ./WinArch.csproj

test:
  stage: test
  script:
    - dotnet restore ./WinArch.csproj
    - dotnet test ./WinArch.csproj

release:
  stage: release
  only:
    - master
  artifacts:
    paths:
      - publish/
  script:
    - dotnet restore ./WinArch.csproj
    - dotnet publish -c Release -o publish -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:DebugType=None ./WinArch.csproj
