//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinArch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinArch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] archlinux_logo_large {
            get {
                object obj = ResourceManager.GetObject("archlinux-logo-large", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] autorun {
            get {
                object obj = ResourceManager.GetObject("autorun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] budgie {
            get {
                object obj = ResourceManager.GetObject("budgie", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] cinnamon {
            get {
                object obj = ResourceManager.GetObject("cinnamon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dde {
            get {
                object obj = ResourceManager.GetObject("dde", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] epic_games_store {
            get {
                object obj = ResourceManager.GetObject("epic-games-store", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gnome {
            get {
                object obj = ResourceManager.GetObject("gnome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gnome_software {
            get {
                object obj = ResourceManager.GetObject("gnome-software", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] kde {
            get {
                object obj = ResourceManager.GetObject("kde", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANSI-dvorak
        ///amiga-de
        ///amiga-us
        ///apple-a1048-sv
        ///apple-a1243-sv
        ///apple-a1243-sv-fn-reverse
        ///apple-internal-0x0253-sv
        ///apple-internal-0x0253-sv-fn-reverse
        ///applkey
        ///atari-de
        ///atari-se
        ///atari-uk-falcon
        ///atari-us
        ///azerty
        ///backspace
        ///bashkir
        ///be-latin1
        ///bg-cp1251
        ///bg-cp855
        ///bg_bds-cp1251
        ///bg_bds-utf8
        ///bg_pho-cp1251
        ///bg_pho-utf8
        ///br-abnt
        ///br-abnt2
        ///br-latin1-abnt2
        ///br-latin1-us
        ///by
        ///by-cp1251
        ///bywin-cp1251
        ///ca
        ///carpalx
        ///carpalx-full
        ///cf
        ///colemak
        ///croat
        ///ctrl
        ///cz
        ///cz-cp1250
        ///cz-lat2
        ///cz-lat2-prog
        ///cz-qwertz
        ///cz-u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string keymaps {
            get {
                return ResourceManager.GetString("keymaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa_DJ.UTF-8 UTF-8
        ///aa_DJ ISO-8859-1
        ///aa_ER UTF-8
        ///aa_ER@saaho UTF-8
        ///aa_ET UTF-8
        ///af_ZA.UTF-8 UTF-8
        ///af_ZA ISO-8859-1
        ///agr_PE UTF-8
        ///ak_GH UTF-8
        ///am_ET UTF-8
        ///an_ES.UTF-8 UTF-8
        ///an_ES ISO-8859-15
        ///anp_IN UTF-8
        ///ar_AE.UTF-8 UTF-8
        ///ar_AE ISO-8859-6
        ///ar_BH.UTF-8 UTF-8
        ///ar_BH ISO-8859-6
        ///ar_DZ.UTF-8 UTF-8
        ///ar_DZ ISO-8859-6
        ///ar_EG.UTF-8 UTF-8
        ///ar_EG ISO-8859-6
        ///ar_IN UTF-8
        ///ar_IQ.UTF-8 UTF-8
        ///ar_IQ ISO-8859-6
        ///ar_JO.UTF-8 UTF-8
        ///ar_JO ISO-8859-6
        ///ar_KW.UTF-8 UTF-8
        ///ar_KW ISO-8859-6
        ///ar_LB.UTF-8 UTF-8
        ///ar_LB ISO- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string langs {
            get {
                return ResourceManager.GetString("langs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pantheon {
            get {
                object obj = ResourceManager.GetObject("pantheon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa/Abidjan
        ///Africa/Accra
        ///Africa/Algiers
        ///Africa/Bissau
        ///Africa/Cairo
        ///Africa/Casablanca
        ///Africa/Ceuta
        ///Africa/El_Aaiun
        ///Africa/Johannesburg
        ///Africa/Juba
        ///Africa/Khartoum
        ///Africa/Lagos
        ///Africa/Maputo
        ///Africa/Monrovia
        ///Africa/Nairobi
        ///Africa/Ndjamena
        ///Africa/Sao_Tome
        ///Africa/Tripoli
        ///Africa/Tunis
        ///Africa/Windhoek
        ///America/Adak
        ///America/Anchorage
        ///America/Araguaina
        ///America/Argentina/Buenos_Aires
        ///America/Argentina/Catamarca
        ///America/Argentina/Cordoba
        ///America/Argentina/Jujuy
        ///America/Argentina/La_Rioja
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string timezones {
            get {
                return ResourceManager.GetString("timezones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] virt_manager {
            get {
                object obj = ResourceManager.GetObject("virt-manager", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WinArch_icon {
            get {
                object obj = ResourceManager.GetObject("WinArch-icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
